version: '3.4'

services:
  db:
    image: codigopenalcda-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: codigopenalcda
    ports:
      - 3308:3306
    networks:
      - codigopenalcda-networks
    
  codigopenalcda:
    image: codigopenalcda
    build:
      context: .
      dockerfile: CodigoPenalCDA/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - codigopenalcda-networks

networks: 
  codigopenalcda-networks:
    driver: bridge